version: 0.2

phases:
  install:
    commands:
      - echo Installing SAM CLI...
      - npm install -g aws-sam-cli
  build:
    commands:
      - echo Building the application...
      - sam build
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET

artifacts:
  type: zip
  files:
    - packaged.yaml
